// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkdcreyvnvotqxkhccjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZGNyZXl2bnZvdHF4a2hjY2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTQ0MDIsImV4cCI6MjA3Mzk3MDQwMn0.dLpJQX78NV2NHQ8wylAZyDB9bMp2dZ7zy9cOem9HxqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});