name: Typecheck (frontend & backend)

on:
  push:
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install root deps (non-strict)
        run: npm install --no-fund --no-audit

      - name: Frontend typecheck
        run: npm run typecheck:frontend

      - name: Install backend deps (non-strict)
        working-directory: backend
        run: npm install --no-fund --no-audit

      - name: Backend typecheck
        working-directory: backend
        run: npx tsc --noEmit -p tsconfig.smoke.json
